algoritmo "Banner"
// Função :
// Autor :
// Data : 16/05/2022
// Seção de Declarações 
var

procedimento banner
inicio
escreval (" ,ggggggggggg,                                                                                              ")
escreval ("dP'''88''''''Y8,                                                                           I8               ")
escreval ("Yb,  88      `8b                                                                           I8               ")
escreval (" `'  88      ,8P                                                                        88888888            ")
escreval ("     88aaaad8P'                                                                            I8               ")
escreval ("     88''''Y8ba    ,ggggg,    ,ggg,,ggg,,ggg,          gg,gggg,     ,gggggg,    ,gggg,gg   I8     ,ggggg,   ")
escreval ("     88      `8b  dP'  'Y8ggg,8' '8P' '8P' '8,         I8P'  'Yb    dP''''8I   dP'  'Y8I   I8    dP'  'Y8ggg")
escreval ("     88      ,8P i8'    ,8I  I8   8I   8I   8I         I8'    ,8i  ,8'    8I  i8'    ,8I  ,I8,  i8'    ,8I  ")
escreval ("     88_____,d8',d8,   ,d8' ,dP   8I   8I   Yb,       ,I8 _  ,d8' ,dP     Y8,,d8,   ,d8b,,d88b,,d8,   ,d8'  ")
escreval ("    88888888P'  P'Y8888P'   8P'   8I   8I   `Y8      P I8 YY88888P8P      `Y8P'Y8888P'`Y88P''Y8P'Y8888P'    ")
escreval ("                                                       I8                                                   ")
escreval ("                                                       I8                                                   ")
escreval ("                                                       I8                                                   ")
escreval ("                                                       I8                                                   ")
escreval ("                                                       I8                                                   ")
escreval ("                                                       I8                                                   ")
fimprocedimento
inicio
      banner
fimalgoritmo
