algoritmo "Calculadora"
// Função :
// Autor :
// Data : 22/01/2022
// Seção de Declarações 
var
 nome: caractere
 n1, n2: inteiro
inicio
escreva ("Qual seu nome?")
leia (nome)
escreval ("Prazer ", nome, ". Como vai?")
escreval
escreval ("Sou Carl, a calculadora. Entendeu o trocadilho? 'Carlculadora'. ")
escreva ("Me manda um número ", nome, ":")
leia (n1)
escreval
escreva ("Coloca outro:")
leia (n2)
escreval
escreval ("Muito fácil, a soma de", n1, " e", n2, " é:", n1 + n2, ".")
escreval ("Você realmente precisa de uma calculadora pra isso? Burrão!")
escreva ("Falou")
escreval
escreval
fimalgoritmo
