algoritmo "semnome"
// Função :
// Autor :
// Data : 02/06/2022
// Seção de Declarações 
var
   a, r, resp: real

funcao calculo (raio, altura:real) : real
       retorne (raio^2 * 3.14 * altura)
fimfuncao
inicio
      escreval ("==================================")
      escreval ("        VOLUME DO CILINDRO        ")
      escreval ("==================================")
      escreva ("Informe o RAIO do cilindro: ")
      leia (r)
      escreva ("Informe a altura do cilindro: ")
      leia (a)
      resp <- calculo (r,a)
      escreval ("----------------------------------")
      escreval ("O volume do cilindro é:", resp)
      escreval ("==================================")
      escreval
      escreval
      escreval
      escreval
      
fimalgoritmo

raio ^2 . phi . altura
